import type { Linter } from 'eslint';
import jsonSchemaValidatorPlugin from 'eslint-plugin-json-schema-validator';
import packageJsonPlugin from 'eslint-plugin-package-json';
import * as jsoncParser from 'jsonc-eslint-parser';

export const packageJsonConfig = {
    files: [ '**/package.json' ],
    languageOptions: { parser: jsoncParser },
    plugins: {
        'package-json': packageJsonPlugin,
        'json-schema-validator': jsonSchemaValidatorPlugin
    },
    rules: {
        'package-json/no-empty-fields': 'error',
        'package-json/no-redundant-files': 'error',
        'package-json/no-redundant-publishConfig': 'error',
        'package-json/repository-shorthand': 'error',
        'package-json/restrict-private-properties': 'error',
        'package-json/scripts-name-casing': 'error',
        'package-json/sort-collections': 'error',
        'package-json/unique-dependencies': 'error',
        'package-json/valid-author': 'error',
        'package-json/valid-bin': 'error',
        'package-json/valid-browser': 'error',
        'package-json/valid-bugs': 'error',
        'package-json/valid-bundleDependencies': 'error',
        'package-json/valid-config': 'error',
        'package-json/valid-contributors': 'error',
        'package-json/valid-cpu': 'error',
        'package-json/valid-dependencies': 'error',
        'package-json/valid-description': 'error',
        'package-json/valid-devDependencies': 'error',
        'package-json/valid-devEngines': 'error',
        'package-json/valid-directories': 'error',
        'package-json/valid-engines': 'error',
        'package-json/valid-exports': 'error',
        'package-json/valid-files': 'error',
        'package-json/valid-funding': 'error',
        'package-json/valid-gypfile': 'error',
        'package-json/valid-homepage': 'error',
        'package-json/valid-keywords': 'error',
        'package-json/valid-libc': 'error',
        'package-json/valid-license': 'error',
        'package-json/valid-main': 'error',
        'package-json/valid-man': 'error',
        'package-json/valid-module': 'error',
        'package-json/valid-name': 'error',
        'package-json/valid-optionalDependencies': 'error',
        'package-json/valid-os': 'error',
        'package-json/valid-packageManager': 'error',
        'package-json/valid-peerDependencies': 'error',
        'package-json/valid-peerDependenciesMeta': 'error',
        'package-json/valid-peerDependenciesMeta-relationship': 'error',
        'package-json/valid-private': 'error',
        'package-json/valid-publishConfig': 'error',
        'package-json/valid-repository': 'error',
        'package-json/valid-repository-directory': 'error',
        'package-json/valid-scripts': 'error',
        'package-json/valid-sideEffects': 'error',
        'package-json/valid-type': 'error',
        'package-json/valid-version': 'error',
        'package-json/valid-workspaces': 'error',

        // Too opinionated for a base preset — consumers can opt in.
        'package-json/bin-name-casing': 'off',
        'package-json/exports-subpaths-style': 'off',
        'package-json/no-local-dependencies': 'off',
        'package-json/order-properties': 'off',
        'package-json/require-attribution': 'off',
        'package-json/require-author': 'off',
        'package-json/require-bin': 'off',
        'package-json/require-browser': 'off',
        'package-json/require-bugs': 'off',
        'package-json/require-bundleDependencies': 'off',
        'package-json/require-config': 'off',
        'package-json/require-contributors': 'off',
        'package-json/require-cpu': 'off',
        'package-json/require-dependencies': 'off',
        'package-json/require-description': 'off',
        'package-json/require-devDependencies': 'off',
        'package-json/require-devEngines': 'off',
        'package-json/require-directories': 'off',
        'package-json/require-engines': 'off',
        'package-json/require-exports': 'off',
        'package-json/require-files': 'off',
        'package-json/require-funding': 'off',
        'package-json/require-gypfile': 'off',
        'package-json/require-homepage': 'off',
        'package-json/require-keywords': 'off',
        'package-json/require-libc': 'off',
        'package-json/require-license': 'off',
        'package-json/require-main': 'off',
        'package-json/require-man': 'off',
        'package-json/require-module': 'off',
        'package-json/require-name': 'off',
        'package-json/require-optionalDependencies': 'off',
        'package-json/require-os': 'off',
        'package-json/require-packageManager': 'off',
        'package-json/require-peerDependencies': 'off',
        'package-json/require-peerDependenciesMeta': 'off',
        'package-json/require-private': 'off',
        'package-json/require-publishConfig': 'off',
        'package-json/require-repository': 'off',
        'package-json/require-scripts': 'off',
        'package-json/require-sideEffects': 'off',
        'package-json/require-type': 'off',
        'package-json/require-types': 'off',
        'package-json/require-version': 'off',
        'package-json/restrict-dependency-ranges': 'off',
        'package-json/restrict-top-level-properties': 'off',
        'package-json/specify-peers-locally': 'off',

        'json-schema-validator/no-invalid': 'error'
    }
} as Linter.Config;
