---
name: Continuous integration

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Node v22
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
            - name: Install dependencies
              run: npm clean-install
            - name: Static code analysis
              run: npx just lint
            - name: Run tests
              run: npx just test
